export const TAROT_DECK_DATA = [
  // Major Arcana (22 cards)
  { id: 0, name: "愚人", nameEn: "The Fool" },
  { id: 1, name: "魔术师", nameEn: "The Magician" },
  { id: 2, name: "女祭司", nameEn: "The High Priestess" },
  { id: 3, name: "皇后", nameEn: "The Empress" },
  { id: 4, name: "皇帝", nameEn: "The Emperor" },
  { id: 5, name: "教皇", nameEn: "The Hierophant" },
  { id: 6, name: "恋人", nameEn: "The Lovers" },
  { id: 7, name: "战车", nameEn: "The Chariot" },
  { id: 8, name: "力量", nameEn: "Strength" },
  { id: 9, name: "隐士", nameEn: "The Hermit" },
  { id: 10, name: "命运之轮", nameEn: "Wheel of Fortune" },
  { id: 11, name: "正义", nameEn: "Justice" },
  { id: 12, name: "倒吊人", nameEn: "The Hanged Man" },
  { id: 13, name: "死神", nameEn: "Death" },
  { id: 14, name: "节制", nameEn: "Temperance" },
  { id: 15, name: "恶魔", nameEn: "The Devil" },
  { id: 16, name: "高塔", nameEn: "The Tower" },
  { id: 17, name: "星星", nameEn: "The Star" },
  { id: 18, name: "月亮", nameEn: "The Moon" },
  { id: 19, name: "太阳", nameEn: "The Sun" },
  { id: 20, name: "审判", nameEn: "Judgement" },
  { id: 21, name: "世界", nameEn: "The World" },
  // Minor Arcana - Wands (14)
  { id: 22, name: "权杖王牌", nameEn: "Ace of Wands" },
  { id: 23, name: "权杖二", nameEn: "Two of Wands" },
  { id: 24, name: "权杖三", nameEn: "Three of Wands" },
  { id: 25, name: "权杖四", nameEn: "Four of Wands" },
  { id: 26, name: "权杖五", nameEn: "Five of Wands" },
  { id: 27, name: "权杖六", nameEn: "Six of Wands" },
  { id: 28, name: "权杖七", nameEn: "Seven of Wands" },
  { id: 29, name: "权杖八", nameEn: "Eight of Wands" },
  { id: 30, name: "权杖九", nameEn: "Nine of Wands" },
  { id: 31, name: "权杖十", nameEn: "Ten of Wands" },
  { id: 32, name: "权杖侍从", nameEn: "Page of Wands" },
  { id: 33, name: "权杖骑士", nameEn: "Knight of Wands" },
  { id: 34, name: "权杖王后", nameEn: "Queen of Wands" },
  { id: 35, name: "权杖国王", nameEn: "King of Wands" },
  // Minor Arcana - Cups (14)
  { id: 36, name: "圣杯王牌", nameEn: "Ace of Cups" },
  { id: 37, name: "圣杯二", nameEn: "Two of Cups" },
  { id: 38, name: "圣杯三", nameEn: "Three of Cups" },
  { id: 39, name: "圣杯四", nameEn: "Four of Cups" },
  { id: 40, name: "圣杯五", nameEn: "Five of Cups" },
  { id: 41, name: "圣杯六", nameEn: "Six of Cups" },
  { id: 42, name: "圣杯七", nameEn: "Seven of Cups" },
  { id: 43, name: "圣杯八", nameEn: "Eight of Cups" },
  { id: 44, name: "圣杯九", nameEn: "Nine of Cups" },
  { id: 45, name: "圣杯十", nameEn: "Ten of Cups" },
  { id: 46, name: "圣杯侍从", nameEn: "Page of Cups" },
  { id: 47, name: "圣杯骑士", nameEn: "Knight of Cups" },
  { id: 48, name: "圣杯王后", nameEn: "Queen of Cups" },
  { id: 49, name: "圣杯国王", nameEn: "King of Cups" },
  // Minor Arcana - Swords (14)
  { id: 50, name: "宝剑王牌", nameEn: "Ace of Swords" },
  { id: 51, name: "宝剑二", nameEn: "Two of Swords" },
  { id: 52, name: "宝剑三", nameEn: "Three of Swords" },
  { id: 53, name: "宝剑四", nameEn: "Four of Swords" },
  { id: 54, name: "宝剑五", nameEn: "Five of Swords" },
  { id: 55, name: "宝剑六", nameEn: "Six of Swords" },
  { id: 56, name: "宝剑七", nameEn: "Seven of Swords" },
  { id: 57, name: "宝剑八", nameEn: "Eight of Swords" },
  { id: 58, name: "宝剑九", nameEn: "Nine of Swords" },
  { id: 59, name: "宝剑十", nameEn: "Ten of Swords" },
  { id: 60, name: "宝剑侍从", nameEn: "Page of Swords" },
  { id: 61, name: "宝剑骑士", nameEn: "Knight of Swords" },
  { id: 62, name: "宝剑王后", nameEn: "Queen of Swords" },
  { id: 63, name: "宝剑国王", nameEn: "King of Swords" },
  // Minor Arcana - Pentacles (14)
  { id: 64, name: "星币王牌", nameEn: "Ace of Pentacles" },
  { id: 65, name: "星币二", nameEn: "Two of Pentacles" },
  { id: 66, name: "星币三", nameEn: "Three of Pentacles" },
  { id: 67, name: "星币四", nameEn: "Four of Pentacles" },
  { id: 68, name: "星币五", nameEn: "Five of Pentacles" },
  { id: 69, name: "星币六", nameEn: "Six of Pentacles" },
  { id: 70, name: "星币七", nameEn: "Seven of Pentacles" },
  { id: 71, name: "星币八", nameEn: "Eight of Pentacles" },
  { id: 72, name: "星币九", nameEn: "Nine of Pentacles" },
  { id: 73, name: "星币十", nameEn: "Ten of Pentacles" },
  { id: 74, name: "星币侍从", nameEn: "Page of Pentacles" },
  { id: 75, name: "星币骑士", nameEn: "Knight of Pentacles" },
  { id: 76, name: "星币王后", nameEn: "Queen of Pentacles" },
  { id: 77, name: "星币国王", nameEn: "King of Pentacles" },
];